server:
  port: 8080

logging:
  level:
    web: debug

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-security
          uri: http://localhost:8081
          predicates:
            - Path=/auth2/**
          filters:
            - LoggingFilter

        - id: ms-security
          uri: http://localhost:8081
          predicates:
            - Path=/persons/**
          filters:
            - LoggingFilter

        - id: ms-persons
          uri: http://localhost:8082
          predicates:
            - Path=/person/**
          filters:
            - LoggingFilter

        - id: ms-persons
          uri: http://localhost:8082
          predicates:
            - Path=/personBus/**
          filters:
            - LoggingFilter

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
          filters:
            - LoggingFilter

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/lista/**
          filters:
            - LoggingFilter

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/category/**
          filters:
            - LoggingFilter
