server:
  port: 8080

logging:
  level:
    web: debug
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-security
          uri: http://localhost:8081
          predicates:
            - Path=/auth2/**

        - id: ms-security
          uri: http://localhost:8081
          predicates:
            - Path=/persons/**

        - id: ms-person
          uri: http://localhost:8082
          predicates:
            - Path=/person/**

        - id: ms-person
          uri: http://localhost:8082
          predicates:
            - Path=/personBus/**

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/products/**

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/lista/**

        - id: ms-store
          uri: http://localhost:8083
          predicates:
            - Path=/category/**
